import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Clone Shoopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello</h2>
    </div>
  )
}
